services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: NL-Lager
    volumes:
      - ./:/var/www/html
    ports:
      - "9090:9090"
    networks:
      - app-network

  web:
    image: nginx:latest
    container_name: Web-Server-NLL
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: DB-NL
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Sumafelo
      MYSQL_DATABASE: IMS_NL
      MYSQL_USER: IMS_Admin
      MYSQL_PASSWORD: Sumafelo03!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: