<?php

namespace ContainerYjZJPlx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewItemControllergenerateInputService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ru_uxYe.App\Controller\NewItemController::generateInput()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ru_uxYe.App\\Controller\\NewItemController::generateInput()'] = ($container->privates['.service_locator.Ru_uxYe'] ?? $container->load('get_ServiceLocator_RuUxYeService'))->withContext('App\\Controller\\NewItemController::generateInput()', $container);
    }
}
