<?php

namespace ContainerXkrZfLr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R17uNlmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r17uNlm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r17uNlm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\BarcodeGeneratorController::show' => ['privates', '.service_locator.Ru_uxYe.App\\Controller\\BarcodeGeneratorController::show()', 'getBarcodeGeneratorControllershowService', true],
            'App\\Controller\\DashboardController::dashboard' => ['privates', '.service_locator.fx2vVXc.App\\Controller\\DashboardController::dashboard()', 'getDashboardControllerdashboardService', true],
            'App\\Controller\\NewItemController::generateInput' => ['privates', '.service_locator.Ru_uxYe.App\\Controller\\NewItemController::generateInput()', 'getNewItemControllergenerateInputService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\BarcodeGeneratorController:show' => ['privates', '.service_locator.Ru_uxYe.App\\Controller\\BarcodeGeneratorController::show()', 'getBarcodeGeneratorControllershowService', true],
            'App\\Controller\\DashboardController:dashboard' => ['privates', '.service_locator.fx2vVXc.App\\Controller\\DashboardController::dashboard()', 'getDashboardControllerdashboardService', true],
            'App\\Controller\\NewItemController:generateInput' => ['privates', '.service_locator.Ru_uxYe.App\\Controller\\NewItemController::generateInput()', 'getNewItemControllergenerateInputService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\BarcodeGeneratorController::show' => '?',
            'App\\Controller\\DashboardController::dashboard' => '?',
            'App\\Controller\\NewItemController::generateInput' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\BarcodeGeneratorController:show' => '?',
            'App\\Controller\\DashboardController:dashboard' => '?',
            'App\\Controller\\NewItemController:generateInput' => '?',
        ]);
    }
}
