<?php

namespace ContainerXkrZfLr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBarcodeGeneratorControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ru_uxYe.App\Controller\BarcodeGeneratorController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.Ru_uxYe'] ?? $container->load('get_ServiceLocator_RuUxYeService'));

        if (isset($container->privates['.service_locator.Ru_uxYe.App\\Controller\\BarcodeGeneratorController::show()'])) {
            return $container->privates['.service_locator.Ru_uxYe.App\\Controller\\BarcodeGeneratorController::show()'];
        }

        return $container->privates['.service_locator.Ru_uxYe.App\\Controller\\BarcodeGeneratorController::show()'] = $a->withContext('App\\Controller\\BarcodeGeneratorController::show()', $container);
    }
}
