<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8W96Upt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8W96Upt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8W96Upt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8W96Upt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8W96Upt\App_KernelDevDebugContainer([
    'container.build_hash' => '8W96Upt',
    'container.build_id' => '2b9ba68c',
    'container.build_time' => 1731593662,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8W96Upt');
