<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN83Rqx7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN83Rqx7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN83Rqx7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN83Rqx7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN83Rqx7\App_KernelDevDebugContainer([
    'container.build_hash' => 'N83Rqx7',
    'container.build_id' => '2b51c6ec',
    'container.build_time' => 1731651858,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN83Rqx7');
