<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYjZJPlx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYjZJPlx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYjZJPlx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYjZJPlx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYjZJPlx\App_KernelDevDebugContainer([
    'container.build_hash' => 'YjZJPlx',
    'container.build_id' => 'ff4308c1',
    'container.build_time' => 1730906974,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYjZJPlx');
