<?php

namespace ContainerNVWpkuc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerdashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fx2vVXc.App\Controller\DashboardController::dashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fx2vVXc.App\\Controller\\DashboardController::dashboard()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'itemRepository' => ['privates', 'App\\Repository\\ItemRepository', 'getItemRepositoryService', true],
        ], [
            'itemRepository' => 'App\\Repository\\ItemRepository',
        ]))->withContext('App\\Controller\\DashboardController::dashboard()', $container);
    }
}
